---

- name: Prepare Statsdaemon directory
  file: state=directory path={{statsdaemon_home}}

- name: Install statsdaemon pt. 1
  get_url:
    url: https://github.com/bitly/statsdaemon/releases/download/v{{statsdaemon_version}}/statsdaemon-{{statsdaemon_version}}.linux-amd64.go1.4.2.tar.gz
    dest: "{{statsdaemon_home}}/statsdaemon-{{statsdaemon_version}}.linux-amd64.go1.4.2.tar.gz"

- name: Install statsdaemon pt. 2
  unarchive:
    src: "{{statsdaemon_home}}/statsdaemon-{{statsdaemon_version}}.linux-amd64.go1.4.2.tar.gz"
    dest: "{{statsdaemon_home}}"
    copy: no
    creates: "{{statsdaemon_home}}/statsdaemon-{{statsdaemon_version}}.linux-amd64.go1.4.2"

- name: Setup statsdaemon service
  template: src=upstart.conf.j2 dest=/etc/init/statsdaemon.conf
  when: statsdaemon_service == 'upstart'
  notify: statsdaemon restart

- name: Setup statsdaemon service
  template: src=systemd.conf.j2 dest=/etc/systemd/system/statsdaemon.service
  when: statsdaemon_service == 'systemd'
  notify: statsdaemon restart

- name: Ensure that Statsdaemon is started
  service: name=statsdaemon state=started enabled=yes
